name: Maintenance_Mode
version: '${project.version}'
main: org.ncc.maintenance_mode.Main
api-version: '1.19'
folia-supported: true

commands:
  smode:
    permission: smode.command

permissions:
  smode.command:
    default: op
  smode.ignore:
    default: op
    description: Permission to make plugin be ignored to kick you when in maintenance
